# Generated by Django 4.1.7 on 2023-03-03 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='yr',
            new_name='year',
        ),
    ]
