# Generated by Django 4.1.7 on 2023-03-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_app', '0002_rename_yr_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='dddd', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
